### ISSUE TITLE
Tedee Local Network API

### ISSUE THREAD

**Issue by SebastianOsinski** [patrickhilker/tedee_hass_integration#41]
Tedee just released preview of local REST API for controlling locks. Do you think the integration should switch to this API when it becomes widely available or should it become a separate integration?

[Documentation](https://docs.tedee.com/bridge-api)

![image](https://github.com/patrickhilker/tedee_hass_integration/assets/2934986/746a5c64-d0fd-4ac6-aede-b95154c9dd19)

![image](https://github.com/patrickhilker/tedee_hass_integration/assets/2934986/3cd31e19-9c14-4641-9c4d-d1f188159f8b)

![image](https://github.com/patrickhilker/tedee_hass_integration/assets/2934986/97cf7491-0b49-4ed5-b561-4701298b55c6)

**Comment by bzumik1** [comment]
That is awesome, after so much time it is finally out!

**Comment by zweckj** [comment]
Already implemented in [2023.11.1b1](https://github.com/patrickhilker/tedee_hass_integration/releases/tag/2023.11.1b1)

**Comment by bzumik1** [comment]
Perfect, thanks so much!

**Comment by vytautasgimbutas** [comment]
@zweckj shouldn't the status updates from manually operating the lock be instant? I'm on 2023.11.0b2 and sometimes status updates can take 5-15secs.

**Comment by zweckj** [comment]
> @zweckj shouldn't the status updates from manually operating the lock be instant? I'm on 2023.11.0b2 and sometimes status updates can take 5-15secs.

yes, but beta.

**Comment by FeromonDE** [comment]
if you open it through the service "unlock", the lock opens but with an error in the log.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:29:09 (2 occurrences)
Last logged: 14:31:39

[139639215195328] Failed to unlock the door. Lock xxxxx
[139639148755520] Failed to unlock the door. Lock xxxxx
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pytedee_async/tedee_client.py", line 325, in _local_api_call
    r = await http_request(
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytedee_async/helpers.py", line 44, in http_request
    return await handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytedee_async/helpers.py", line 64, in handle_response
    raise TedeeClientException(
pytedee_async.exception.TedeeClientException: Error during HTTP request. Status code 406

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tedee/lock.py", line 144, in async_unlock
    await self.coordinator.tedee_client.unlock(self._lock.lock_id)
  File "/usr/local/lib/python3.11/site-packages/pytedee_async/tedee_client.py", line 220, in unlock
    local_call_success, _ = await self._local_api_call(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytedee_async/tedee_client.py", line 348, in _local_api_call
    raise TedeeDataUpdateException(
pytedee_async.exception.TedeeDataUpdateException: Error while calling local API endpoint /lock/xxxxxx/unlock?mode=3.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 111, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/tedee/lock.py", line 147, in async_unlock
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to unlock the door. Lock xxxxx
```

**Comment by darkkatarsis** [comment]
I tested the local api a bit and overall it works very smoothly except for the status update. I have the impression that it behaves a bit as if the cloud is being queried after closing open because the status will change after a few seconds from when it actually closed open. Is this a feature or a bug ?

**Comment by zweckj** [comment]
> Is this a feature or a bug ?
HA queries the bridge (and if it can't reach that, the cloud - if configured) every couple of seconds, that's when you receive the update. 
Push updates appear to be broken. Somebody - either tedee or Home Assistant - changed something and push updates stopped working.

**Comment by zweckj** [comment]
Starting with HomeAssistant 2024.2 a tedee integration which supports the local API will be part of HomeAssistant core, development of the local API here will not be taken further (at least not by me).
