### ISSUE TITLE
Push updates broken in HA 2023.12

### ISSUE THREAD

**Issue by zweckj** [patrickhilker/tedee_hass_integration#52]
Push updates are broken in 2023.12, this seems to come from the updated aiohttp. 

```

2023-12-15 18:56:42.440 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 350, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
Data after `Connection: close`:
b'{"event":"lock-status-changed","timestamp":"2023-12-15T17:56:40.776Z","data":{"deviceType":2,"deviceId":xxxx,"serialNumber":"xxxxxx","state":8,"jammed":0}}\x00'

```

Edit: Webhook request have a trailing \0 which aiohttp 3.9 doesn't like. Waiting for firmware update from tedee.

**Comment by zweckj** [comment]
tedee local API will move to HA core, that part won't be fixed here
